apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-staging
  labels:
    app: argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
