apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3  # Number of replicas/pods you want
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 8080 
        volumeMounts:
          - name: shared-volume
            mountPath: /data/dvs  
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: test-pvc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Allows multiple pods to read and write
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
  storageClassName: standard
  volumeMode: Filesystem
