image: elasticsearch:7.17.9

name: elasticsearch

tcpPort: 9200

transportPort: 9300

replicas: 1

clusterName: vd

minHeap: "-Xms512m" 

maxHeap: "-Xmx512m"

password: c58d66dd8637

resources:
  requests:
    memory: 250Mi
    cpu: 150m
  limits:
    memory: 1Gi
    cpu: 250m

persistence:
  size: 50Gi

nodeSelector:
  enabled: false
  key: application
  value: infrastructure
  

