image: elasticsearch:7.17.9
name: elasticsearch

tcpPort: 9200

transportPort: 9300

replicas: 1

clusterName: argocd_cluster

minHeap: "-Xms512m" 

maxHeap: "-Xmx512m"

password: argocdhelm

resources:
  requests:
    memory: 250Mi
    cpu: 150m
  limits:
    memory: 1Gi
    cpu: 250m

persistence:
  size: 20Gi

nodeSelector:
  enabled: false
  key: application
  value: infrastructure
  

