apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}
    release: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}
      release: {{ .Values.name }}
  serviceName: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}
        release: {{ .Values.name }}
    spec:
      containers:
      - env:
        - name: cluster.name
          value: {{ .Values.clusterName }}
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: {{ .Values.minHeap }} {{ .Values.maxHeap }}
        - name: bootstrap.memory_lock
          value: "false"
        - name: ELASTIC_PASSWORD
          value: {{ .Values.password }}
        - name: xpack.security.enabled
          value: "true"
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.tcpPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.transportPort }}
          name: transport
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}        
        securityContext:
          privileged: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        - sysctl -w vm.max_map_count=262144
        - chmod 777 /usr/share/elasticsearch/data
        - chmod 777 /usr/share/elasticsearch/data/node
        - chmod 777 /usr/share/elasticsearch/data/backup
        - chmod g+rwx /usr/share/elasticsearch/data
        - chmod g+rwx /usr/share/elasticsearch/data/backup
        - chgrp 1000 /usr/share/elasticsearch/data
        - chgrp 1000 /usr/share/elasticsearch/data/backup
        image: busybox:1.29.2
        imagePullPolicy: IfNotPresent
        name: set-dir-owner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      storageClassName: manual
      volumeMode: Filesystem
